service: cv-backend

plugins:
    - serverless-secrets-plugin

provider:
    name: aws
    runtime: nodejs6.10
    stage: dev
    region: us-west-2
    environment:
        EMAIL_FROM: ${self:custom.secrets.EMAIL_FROM}
        EMAIL_TO: ${self:custom.secrets.EMAIL_TO}
        RECAPTCHA_SECRET: ${self:custom.secrets.RECAPTCHA_SECRET}
    iamRoleStatements:
        - Effect: "Allow"
          Action:
              - "ses:SendEmail"
              - "ses:SendEmailRaw"
          Resource:
              - "*"

custom:
    secrets: ${file(secrets.${opt:stage, self:provider.stage}.yml)}

functions:
    sendMail:
        handler: handler.sendMail
        events:
            - http:
                path: mail
                method: post
                cors: true
